baseURL = "https://lizardsec.xyz/"
languageCode = "pt-br"
title = "LizardSec"
theme = "terminal"

[params]
  # Opções de cor: orange, blue, red, green, pink
  themeColor = "green"
  customCSS = ["css/custom.css"]
  favicon = "favicon.png"
  # O que aparece no "prompt" do terminal no site
  prompt = "root@lizardsec:~#"
  
  # Configurações de exibição
  showFullContent = false
  summaryLength = 0
  readingTime = true
  fullWidthContent = true

[[menu.main]]
  name = "</Posts>"
  url = "/posts"

[[menu.main]]
  name = "</About>"
  url = "/about"

[[params.social]]
    name = "github"
    url = "https://github.com/0xl1z4rd"

[[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/andmoraes/"
